# Site settings
title: Ebeltoft Marineforening
email: info@grenaamarineforening.dk
description: > # Marineforeningen for Grenaa og Omegn. Foreningens formål er at styrke nationens interesse for SØVÆRNET og SØFARTEN ved fælles arbejde for denne sag,
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

collections:
  sider:
    output: true
    permalink: /:title/index.html

# Include og exclude
# include: ['']
exclude: ['Gemfile', 'gemfile.lock', 'CNAME']

# Prose
prose:
  media: /assets/img/
  siteurl: http://odderinfo.netlify.com/
  ignore:
    - .gitattributes
    - 404.html
    - Gemfile
    - gemfile.lock
    - .gitignore
    - _config.yml
    - index.html
    - _includes
    - _plugins
    - _site
    - assets
    - _layouts
    - sider
    - CNAME
    - _data

  metadata:
    "_sider":
      - name: "title"
        field:
          element: "text"
          label: "title"
          help: "Skriv en title på siden, max 49 tegn"



# Standart indstillinger for sider
defaults:
  -
    scope:
      parth: "sider"
    values:
      layout: "normal-side"
